spring.application.name=event-management-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/event_management
spring.datasource.username=event_user
spring.datasource.password=event_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080

jwt.secret=9J8mP2xR7vN4kQ1sT6yW3cF8hL5zB0uD2pM7nX4aV9eC1rK6
jwt.expiration=86400000
