import { Icon } from "./Icons";
function fmt(value){return value ? new Date(value).toLocaleString("sr-RS",{dateStyle:"medium",timeStyle:"short"}) : "Nije definisano"}
export default function EventDetails({ event, currentUser, isParticipant, canEdit, registrations, users, onBack, onEdit, onDelete, onRegister, onCancelRegistration }) {
  const mine = registrations.filter(r => r.userId === currentUser.userId);
  const activeMine = mine.find(r => r.status !== "CANCELLED");
  return <div className="view-stack"><button className="text-btn detail-back" onClick={onBack}><Icon name="back"/>Nazad na događaje</button><section className="event-hero-detail"><div className="detail-content"><span className="eyebrow">Detalji događaja</span><h1>{event.title}</h1><p>{event.description || "Opis događaja nije unet."}</p><div className="detail-meta"><span><Icon name="map"/>{event.location}</span><span><Icon name="clock"/>{fmt(event.startTime)}</span><span><Icon name="users"/>{event.organizerUsername || "Organizator nije naveden"}</span></div></div><div className="capacity-card"><small>Raspoloživa mesta</small><strong>{event.availableSpots}<span> / {event.capacity}</span></strong><div className="progress"><i style={{width:`${Math.max(0,Math.min(100,(event.availableSpots/event.capacity)*100))}%`}}/></div><p>{event.availableSpots > 0 ? "Prijave su otvorene" : "Kapacitet je popunjen"}</p></div></section>
  <section className="detail-actions-bar">{canEdit && <><button className="secondary-btn" onClick={onEdit}><Icon name="edit"/>Izmeni</button><button className="danger-btn" onClick={onDelete}><Icon name="trash"/>Obriši</button></>}{isParticipant && !activeMine && <><button className="primary-btn" onClick={() => onRegister("optimistic")}>Prijavi se</button><button className="secondary-btn" onClick={() => onRegister("pessimistic")}>Pessimistic prijava</button></>}{isParticipant && activeMine && <div className="registration-state"><span className={`status ${activeMine.status.toLowerCase()}`}>{activeMine.status}</span><button className="danger-link" onClick={() => onCancelRegistration(activeMine.userId)}>Otkaži prijavu</button></div>}</section>
  {!isParticipant && canEdit && <section className="panel-modern"><div className="panel-header"><div><h2>Prijave i lista čekanja</h2><p>Upravljajte prijavljenim učesnicima za ovaj događaj.</p></div><span className="count-badge">{registrations.length}</span></div>{registrations.length===0?<div className="empty-inline">Još nema prijava.</div>:<div className="registration-list">{registrations.map(r=>{const u=users.find(x=>x.id===r.userId);return <div className="registration-row" key={r.id}><span className="avatar small-avatar">{(u?.username || r.userId)?.toString()[0]}</span><div><b>{u?.username || `Korisnik ${r.userId}`}</b><small>ID: {r.userId}</small></div><span className={`status ${r.status.toLowerCase()}`}>{r.status}</span>{r.status!=="CANCELLED"&&<button className="icon-btn danger-icon" onClick={()=>onCancelRegistration(r.userId)}><Icon name="trash" size={17}/></button>}</div>})}</div>}</section>}
  </div>;
}
